image: node:latest

stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/
build:
  stage: build
  script:
    - rm -rf node_modules package-lock.json
    - npm install
    - npm run build
  artifacts:
# 만료 시간을 설정해 줍니다.
    expire_in: 1 hour
# 다음 stage에서 사용할 파일의 경로를 지정해 줍니다.
    paths:
      - ./dist

deploy-to-s3:
  image: python:latest
  stage: deploy
  script:
    - pip install awscli
    - aws s3 sync dist s3://trip-note
  only:
    - dev
  when: manual